# Generated by Django 3.1.3 on 2020-11-10 12:43

from django.db import migrations, models


def create_roles(apps, schema_editor):
    Role = apps.get_model('store', 'Role')
    admin_role = Role.objects.create(name='Admin')
    client_role = Role.objects.create(name='Client')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201104_1230'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
